apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "uptime-kuma.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $idx, $p := .Values.service.ports }}
    - name: {{ $p.name | default (printf "port%d" $idx) }}
      protocol: {{ $p.protocol | default "TCP" }}
      port: {{ $p.port }}
      targetPort: {{ $p.targetPort | default $p.port }}
      {{- if $p.nodePort }}
      nodePort: {{ $p.nodePort }}
      {{- end }}
    {{- end }}
